version: "3.8"

services:

  react_app:
    image: dspalek/eatcarefully-frontend:local
    container_name: react_app
    ports:
      - "3000:80"
    depends_on:
      - spring_app
      - keycloak
    networks:
      - eat_network

  label_analysis_service:
    image: dspalek/eatcarefully-label-service:latest
    container_name: label_analysis_service
    environment:
      API_KEY: ${GEMINI_API_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      GEMINI_MODEL: gemini-1.5-flash
      TEMPERATURE: 1.0
      MAX_OUTPUT_TOKENS: 1000
      INSTRUCTION: "Your responses should always be in valid json that can be parsed by python. Never create nested objects. If answer is more complex answer in few sentences. Do not use lists in response json."
      PROMPT_TASK: "Examine product label: Does it contain harmful ingredients? If so, briefly describe their impact on health. Are there any allergens? Is the product highly processed? Are there food additives? If so, state if they are harmful. Does it contain ingredients that are harmful in excess (e.g., some first listed ingredients)? Is the product vegan, vegetarian, or does it contain gluten?"
      PROMPT_RESPONSE_FORMAT: "Provide a JSON response with the following keys: harmful_ingredients, harmful_in_excess, allergens, is_highly_processed, food_additives, contains_gluten, is_vegan, is_vegetarian. Don't use escape sequences in your response. Do not add anything outside json."
      PROMPT_LABEL_PREFIX: "Label:"
      DB_HOST: localhost
      DB_PORT: 6379
    networks:
      - eat_network

  history_analysis_service:
    image: dspalek/eatcarefully-history-service:latest
    container_name: history_analysis_service
    networks:
      - eat_network

  recommendation_service:
    image: dspalek/eatcarefully-recommendation-service:latest
    container_name: recommendation_service
    volumes:
      - ./recommendation-data:/data
    networks:
      - eat_network

  spring_app:
    build: .
    container_name: spring_app
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker

      SPRING_DATASOURCE_URL: jdbc:postgresql://database_main:5432/eatcarefully
      SPRING_DATASOURCE_USERNAME: ${SPRING_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DB_PASSWORD}

      RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/eat-carefully
      SERVER_HOST: ${SERVER_HOST:-http://localhost}  # default value is 'http://localhost'
      FRONTEND_PORT: ${FRONTEND_PORT:-3000}  # default is 3000 so that default URL is 'http://localhost:3000'
      RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/eat-carefully/protocol/openid-connect/certs
      SECURITY_LOG_LEVEL: ${SECURITY_LOG_LEVEL:-INFO}

      FLYWAY_DISABLE_CLEAN: ${FLYWAY_DISABLE_CLEAN:-true}
      FLYWAY_ENABLE_CLEAN_ON_ERROR: ${FLYWAY_ENABLE_CLEAN_ON_ERROR:-false}

      LABEL_ANALYSIS_SERVICE_HOST: ${LABEL_ANALYSIS_SERVICE_HOST:-XXX.XX.X.X}
      HISTORY_ANALYSIS_SERVICE_HOST: ${HISTORY_ANALYSIS_SERVICE_HOST:-XXX.XX.X.X}
      RECOMMENDATION_SERVICE_HOST: ${RECOMMENDATION_SERVICE_HOST:-XXX.XX.X.X}
      TESSERACT_DATA_PATH: /app/tessdata
      INIT_MOCK_LEADERBOARD: ${INIT_LEADERBOARD:-false}
    depends_on:
      - label_analysis_service
      - history_analysis_service
      - recommendation_service
      - database_main
      - keycloak
    volumes:
      - ./src/main/resources/tessdata:/app/tessdata
    networks:
      - eat_network

  database_main:
    image: postgres:16.6-alpine3.20
    container_name: database_main
    environment:
      POSTGRES_USER: ${SPRING_DB_USER}
      POSTGRES_PASSWORD: ${SPRING_DB_PASSWORD}
      POSTGRES_DB: eatcarefully
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - eat_network

  keycloak:
    container_name: keycloak
    image: bitnami/keycloak:24.0.5
    volumes:
      - ./import/realm:/opt/bitnami/keycloak/data/import
      - ./import/theme:/opt/bitnami/keycloak/providers
    environment:
      KEYCLOAK_DATABASE_HOST: database_keycloak
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_USER: ${KEYCLOAK_DB_USER}
      KEYCLOAK_DATABASE_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_EXTRA_ARGS: "--import-realm"
    ports:
      - "8080:8080"
    depends_on:
      - database_keycloak
    networks:
      - eat_network

  database_keycloak:
    image: postgres:16.6-alpine3.20
    container_name: database_keycloak
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${KEYCLOAK_DB_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      POSTGRES_DB: keycloak
    healthcheck:
      test: "exit 0"
    networks:
      - eat_network


networks:
  eat_network:
volumes:
  postgres_data:


