version: "3.8"

services:

  react_app:
    image: dspalek/eatcarefully-frontend:local
    container_name: react_app
    ports:
      - "3000:80"
    depends_on:
      - spring_app
      - keycloak
    networks:
      - eat_network

  spring_app:
    build: .
    container_name: spring_app
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker

      SPRING_DATASOURCE_URL: jdbc:postgresql://database_main:5432/eatcarefully
      SPRING_DATASOURCE_USERNAME: ${SPRING_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DB_PASSWORD}

      RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/eat-carefully
      SERVER_HOST: ${SERVER_HOST:-http://localhost}  # default value is 'http://localhost'
      FRONTEND_PORT: ${FRONTEND_PORT:-3000}  # default is 3000 so that default URL is 'http://localhost:3000'
      RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/eat-carefully/protocol/openid-connect/certs
      SECURITY_LOG_LEVEL: ${SECURITY_LOG_LEVEL:-INFO}

      TESSERACT_DATA_PATH: /app/tessdata

      FLYWAY_DISABLE_CLEAN: ${FLYWAY_DISABLE_CLEAN:-true}
      FLYWAY_ENABLE_CLEAN_ON_ERROR: ${FLYWAY_ENABLE_CLEAN_ON_ERROR:-false}

      INIT_MOCK_LEADERBOARD: ${INIT_LEADERBOARD:-false}
    depends_on:
      - database_main
      - keycloak
    volumes:
      - ./src/main/resources/tessdata:/app/tessdata
    networks:
      - eat_network

  database_main:
    image: postgres:16.6-alpine3.20
    container_name: database_main
    environment:
      POSTGRES_USER: ${SPRING_DB_USER}
      POSTGRES_PASSWORD: ${SPRING_DB_PASSWORD}
      POSTGRES_DB: eatcarefully
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - eat_network

  keycloak:
    container_name: keycloak
    image: bitnami/keycloak:24.0.5
    volumes:
      - ./import/realm:/opt/bitnami/keycloak/data/import
      - ./import/theme:/opt/bitnami/keycloak/providers
    environment:
      KEYCLOAK_DATABASE_HOST: database_keycloak
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_USER: ${KEYCLOAK_DB_USER}
      KEYCLOAK_DATABASE_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_EXTRA_ARGS: "--import-realm"
    ports:
      - "8080:8080"
    depends_on:
      - database_keycloak
    networks:
      - eat_network

  database_keycloak:
    image: postgres:16.6-alpine3.20
    container_name: database_keycloak
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${KEYCLOAK_DB_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      POSTGRES_DB: keycloak
    healthcheck:
      test: "exit 0"
    networks:
      - eat_network


networks:
  eat_network:
volumes:
  postgres_data:


