spring:
  application:
    name: backend

  # postgres as database
  datasource:
    url: jdbc:postgresql://localhost:6543/eatcarefully
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/eat-carefully
          jwk-set-uri: http://localhost:8080/realms/eat-carefully/protocol/openid-connect/certs

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    clean-disabled: ${FLYWAY_DISABLE_CLEAN:false}
    clean-on-validation-error: ${FLYWAY_ENABLE_CLEAN_ON_ERROR:true}

security:
  enabled: ${SECURITY_ENABLED:true}
  frontend:
    base-url: ${SERVER_HOST:http://localhost}:${FRONTEND_PORT:3000}

jwt:
  auth:
    converter:
      resource-id: backend_client
      principle-attribute: preferred_username

app:
  label-analysis-service:
    url: http://localhost:80/service/analyze-label
  history-analysis-service:
    url: http://localhost:8000/analyze/
  recommendation-service:
    url: http://localhost:8001/api/v1/recommendations/
  init-mock-leaderboard: ${INIT_MOCK_LEADERBOARD:false}

server:
  port: 8081
  servlet:
    context-path: /api

tesseract:
  path: ${TESSERACT_DATA_PATH:classpath:tessdata}

