spring:
  application:
    name: backend

  # postgres as database
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${RESOURCESERVER_JWT_ISSUER_URI:http://keycloak:8080/realms/eat-carefully}
          frontend-issuer-uri: ${SERVER_HOST}:8080/realms/eat-carefully
          jwk-set-uri: ${RESOURCESERVER_JWT_JWK_SET_URI:http://keycloak:8080/realms/eat-carefully/protocol/openid-connect/certs}

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    clean-disabled: ${FLYWAY_DISABLE_CLEAN}
    clean-on-validation-error: ${FLYWAY_ENABLE_CLEAN_ON_ERROR}

security:
  enabled: ${SECURITY_ENABLED:true}
  frontend:
    base-url: ${SERVER_HOST}:${FRONTEND_PORT}


jwt:
  auth:
    converter:
      resource-id: backend_client_docker
      principle-attribute: preferred_username

app:
  label-analysis-service:
    url: ${LABEL_ANALYSIS_SERVICE_URL}
  history-analysis-service:
    url: ${HISTORY_ANALYSIS_SERVICE_URL}
  recommendation-service:
    url: ${RECOMMENDATION_SERVICE_URL}
  init-mock-leaderboard: ${INIT_MOCK_LEADERBOARD}

server:
  port: 8081
  servlet:
    context-path: /api

tesseract:
  path: ${TESSERACT_DATA_PATH}

logging:
  level:
    org:
      springframework:
        security: ${SECURITY_LOG_LEVEL}
