
CREATE TABLE achievement_definition (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    description character varying(255),
    threshold_bronze integer NOT NULL,
    threshold_silver integer NOT NULL,
    threshold_gold integer NOT NULL,
    achievement_type character varying(255) NOT NULL,
    achievement_parameter character varying(255) NOT NULL
);

CREATE TABLE achievement_progress (
    id bigint NOT NULL,
    current_count integer NOT NULL,
    current_level smallint,
    username character varying(255),
    achievement_definition_id bigint,
    CONSTRAINT achievement_progress_current_level_check CHECK (((current_level >= 0) AND (current_level <= 3)))
);

ALTER TABLE achievement_progress ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME achievement_progress_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE allergen (
    id bigint NOT NULL,
    name character varying(255)
);


CREATE SEQUENCE allergen_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



CREATE TABLE category (
    id bigint NOT NULL,
    name character varying(255)
);



ALTER TABLE category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);




CREATE TABLE ingredient (
    id bigint NOT NULL,
    content real,
    description character varying(255),
    name character varying(255)
);


CREATE SEQUENCE ingredient_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



CREATE TABLE leaderboard_position (
    id bigint NOT NULL,
    points integer,
    username character varying(255)
);


ALTER TABLE leaderboard_position ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME leaderboard_position_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE point_event (
    id bigint NOT NULL,
    product_barcode character varying(255),
    username character varying(255)
);


ALTER TABLE point_event ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME point_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE preference_name (
    id bigint NOT NULL,
    name character varying(255)
);


CREATE SEQUENCE preference_name_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



CREATE TABLE product (
    id character varying(255) NOT NULL,
    brand character varying(255),
    imageurl character varying(255),
    name character varying(255),
    nova_group character varying(255),
    score character varying(255)
);


CREATE TABLE product_allergens (
    product_id character varying(255) NOT NULL,
    allergens_id bigint NOT NULL
);


CREATE TABLE product_categories (
    product_id character varying(255) NOT NULL,
    categories_id bigint NOT NULL
);


CREATE TABLE product_ingredients (
    product_id character varying(255) NOT NULL,
    ingredients_id bigint NOT NULL
);


ALTER TABLE product_ingredients OWNER TO postgres;


CREATE TABLE product_tags (
    product_id character varying(255) NOT NULL,
    tags_id bigint NOT NULL
);


CREATE TABLE purchase (
    id bigint NOT NULL,
    purchase_date date,
    username character varying(255)
);


ALTER TABLE purchase ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME purchase_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE purchase_item (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    product_id character varying(255),
    purchase_id bigint
);



ALTER TABLE purchase_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME purchase_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE tag (
    id bigint NOT NULL,
    name character varying(255)
);



CREATE SEQUENCE tag_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;




CREATE TABLE user_nutritional_profile (
    username character varying(255) NOT NULL,
    calories_threshold integer NOT NULL,
    carbohydrates_threshold integer NOT NULL,
    fat_threshold integer NOT NULL,
    protein_threshold integer NOT NULL,
    CONSTRAINT user_nutritional_profile_check CHECK ((((fat_threshold >= 0) AND (fat_threshold <= 5000)) AND ((protein_threshold >= 0) AND (protein_threshold <= 5000)) AND ((carbohydrates_threshold >= 0) AND (carbohydrates_threshold <= 5000)) AND ((calories_threshold >= 0) AND (calories_threshold <= 5000))))
);



CREATE TABLE user_preference (
    preference_name_id bigint NOT NULL,
    username character varying(255) NOT NULL,
    wanted integer NOT NULL
);



ALTER TABLE ONLY achievement_definition
    ADD CONSTRAINT achievement_definition_pkey PRIMARY KEY (id);



ALTER TABLE ONLY achievement_progress
    ADD CONSTRAINT achievement_progress_pkey PRIMARY KEY (id);




ALTER TABLE ONLY allergen
    ADD CONSTRAINT allergen_pkey PRIMARY KEY (id);




ALTER TABLE ONLY category
    ADD CONSTRAINT category_pkey PRIMARY KEY (id);


ALTER TABLE ONLY ingredient
    ADD CONSTRAINT ingredient_pkey PRIMARY KEY (id);



ALTER TABLE ONLY leaderboard_position
    ADD CONSTRAINT leaderboard_position_pkey PRIMARY KEY (id);




ALTER TABLE ONLY point_event
    ADD CONSTRAINT point_event_pkey PRIMARY KEY (id);




ALTER TABLE ONLY preference_name
    ADD CONSTRAINT preference_name_pkey PRIMARY KEY (id);




ALTER TABLE ONLY product
    ADD CONSTRAINT product_pkey PRIMARY KEY (id);




ALTER TABLE ONLY purchase_item
    ADD CONSTRAINT purchase_item_pkey PRIMARY KEY (id);




ALTER TABLE ONLY purchase
    ADD CONSTRAINT purchase_pkey PRIMARY KEY (id);



ALTER TABLE ONLY tag
    ADD CONSTRAINT tag_pkey PRIMARY KEY (id);




ALTER TABLE ONLY category
    ADD CONSTRAINT uk46ccwnsi9409t36lurvtyljak UNIQUE (name);



ALTER TABLE ONLY user_nutritional_profile
    ADD CONSTRAINT user_nutritional_profile_pkey PRIMARY KEY (username);



ALTER TABLE ONLY user_preference
    ADD CONSTRAINT user_preference_pkey PRIMARY KEY (preference_name_id, username);




CREATE INDEX idx_points ON leaderboard_position USING btree (points);




ALTER TABLE ONLY purchase_item
    ADD CONSTRAINT fk1mncc5yaore1sibgpj3jc4a7u FOREIGN KEY (purchase_id) REFERENCES purchase(id);



ALTER TABLE ONLY product_tags
    ADD CONSTRAINT fk37nayk23lk8ibkhrfy8wwbvyo FOREIGN KEY (tags_id) REFERENCES tag(id);



ALTER TABLE ONLY product_allergens
    ADD CONSTRAINT fk392nx0yoewx4de79kwfsnenyp FOREIGN KEY (product_id) REFERENCES product(id);



ALTER TABLE ONLY product_categories
    ADD CONSTRAINT fk86pfomapgvxb87x9nnxuc0pdj FOREIGN KEY (categories_id) REFERENCES category(id);



ALTER TABLE ONLY product_tags
    ADD CONSTRAINT fk8gmf959fnpxtkagtk56mbaj0e FOREIGN KEY (product_id) REFERENCES product(id);




ALTER TABLE ONLY user_preference
    ADD CONSTRAINT fkbhu2f2ncp09e12h5730nsam5r FOREIGN KEY (username) REFERENCES user_nutritional_profile(username);




ALTER TABLE ONLY product_ingredients
    ADD CONSTRAINT fkcjxxp1v84pkvofdwi58x85431 FOREIGN KEY (product_id) REFERENCES product(id);



ALTER TABLE ONLY user_preference
    ADD CONSTRAINT fkesanp4tkvtlxrbgv99cqf5fpk FOREIGN KEY (preference_name_id) REFERENCES preference_name(id);



ALTER TABLE ONLY product_categories
    ADD CONSTRAINT fkppc5s0f38pgb35a32dlgyhorc FOREIGN KEY (product_id) REFERENCES product(id);



ALTER TABLE ONLY product_ingredients
    ADD CONSTRAINT fkq51ay36hx4j4y345v8bkr2dix FOREIGN KEY (ingredients_id) REFERENCES ingredient(id);




ALTER TABLE ONLY purchase_item
    ADD CONSTRAINT fkq69apam78dbi0cggl37ge6auf FOREIGN KEY (product_id) REFERENCES product(id);



ALTER TABLE ONLY product_allergens
    ADD CONSTRAINT fksuwxxijd8kwqyfp8qk446mnxb FOREIGN KEY (allergens_id) REFERENCES allergen(id);



ALTER TABLE ONLY achievement_progress
    ADD CONSTRAINT fktdy61qwbb9rqbv5coseer5674 FOREIGN KEY (achievement_definition_id) REFERENCES achievement_definition(id);

