INSERT INTO achievement_definition (id, name, description, threshold_bronze, threshold_silver, threshold_gold,
                                    achievement_type, achievement_parameter)
VALUES (1, 'Product Explorer', 'Achievement Description Placeholder', 3, 10, 15, 'NONE', ''),
       (2, 'Health Guru', 'Achievement Description Placeholder', 15, 50, 150, 'NUTRI_SCORE', 'A'),
       (3, 'Living on the Edge', 'Achievement Description Placeholder', 10, 30, 100, 'NUTRI_SCORE', 'E'),
       (4, 'Gym Bro', 'Achievement Description Placeholder', 10, 40, 150, 'PRODUCT_NAME', 'Protein'),
       (5, 'Skinny Bro', 'Achievement Description Placeholder', 15, 50, 200, 'PRODUCT_NAME', 'Light'),
       (6, 'Sweet Johnny', 'Achievement Description Placeholder', 10, 35, 100, 'PRODUCT_CATEGORY', 'Sweet snacks'),
       (7, 'Nutella Junkie', 'Achievement Description Placeholder', 3, 8, 15, 'PRODUCT_NAME', 'Nutella'),
       (8, 'Juice Master', 'Achievement Description Placeholder', 10, 30, 100, 'PRODUCT_CATEGORY',
        'Juices and nectars'),
       (9, 'Hydration Expert', 'Achievement Description Placeholder', 5, 15, 40, 'PRODUCT_CATEGORY', 'Waters'),
       (10, 'Bubble Trouble', 'Achievement Description Placeholder', 8, 25, 75, 'PRODUCT_CATEGORY', 'Sodas'),
       (11, 'MONSTER MONSTER', 'Achievement Description Placeholder', 5, 15, 35, 'PRODUCT_NAME', 'Monster Energy'),
       (12, 'Caffeine Addict', 'Achievement Description Placeholder', 10, 35, 100, 'PRODUCT_CATEGORY', 'Coffees'),
       (13, 'Dairy Detective', 'Achievement Description Placeholder', 15, 50, 150, 'PRODUCT_CATEGORY', 'Dairies'),
       (14, 'Milky Dave', 'Achievement Description Placeholder', 5, 15, 40, 'PRODUCT_CATEGORY', 'Milks'),
       (15, 'Cold Palmer', 'Achievement Description Placeholder', 10, 30, 80, 'PRODUCT_CATEGORY', 'Ice creams'),
       (16, 'Huel Enjoyer', 'Achievement Description Placeholder', 20, 75, 150, 'NOVA_SCORE', '4'),
       (17, 'Nature Fan', 'Achievement Description Placeholder', 15, 50, 100, 'NOVA_SCORE', '1'),
       (18, 'Booze Beast', 'Achievement Description Placeholder', 10, 30, 100, 'PRODUCT_CATEGORY', 'Alcohol'),
       (19, 'Are you serious?', 'You better not eat that', 1, 2, 3, 'PRODUCT_NAME', 'Domestos');
