INSERT INTO achievement_definition (id, name, description, threshold_bronze, threshold_silver, threshold_gold)
VALUES (1, 'Product Explorer', 'Achievement Description Placeholder', 3, 10, 15),
       (2, 'Health Guru', 'Achievement Description Placeholder', 15, 50, 150),
       (3, 'Living on the Edge', 'Achievement Description Placeholder', 10, 30, 100),
       (4, 'Gym Bro', 'Achievement Description Placeholder', 10, 40, 150),
       (5, 'Skinny Bro', 'Achievement Description Placeholder', 15, 50, 200),
       (6, 'Sweet Johnny', 'Achievement Description Placeholder', 10, 35, 100),
       (7, 'Nutella Junkie', 'Achievement Description Placeholder', 3, 8, 15),
       (8, 'Juice Master', 'Achievement Description Placeholder', 10, 30, 100),
       (9, 'Hydration Expert', 'Achievement Description Placeholder', 5, 15, 40),
       (10, 'Bubble Trouble', 'Achievement Description Placeholder', 8, 25, 75),
       (11, 'MONSTER MONSTER', 'Achievement Description Placeholder', 5, 15, 35),
       (12, 'Caffeine Addict', 'Achievement Description Placeholder', 10, 35, 100),
       (13, 'Dairy Detective', 'Achievement Description Placeholder', 15, 50, 150),
       (14, 'Milky Dave', 'Achievement Description Placeholder', 5, 15, 40),
       (15, 'Cold Palmer', 'Achievement Description Placeholder', 10, 30, 80),
       (16, 'Huel Enjoyer', 'Achievement Description Placeholder', 20, 75, 150),
       (17, 'Nature Fan', 'Achievement Description Placeholder', 15, 50, 100),
       (18, 'Booze Beast', 'Achievement Description Placeholder', 10, 30, 100),
       (19, '???', 'Achievement Description Placeholder', 10, 30, 100);