INSERT INTO achievement_definition (id, name, description, threshold_bronze, threshold_silver, threshold_gold,
                                    achievement_type, achievement_parameter)
VALUES (1, 'Product Explorer', 'Discover and expand your collection', 10, 50, 200, 'NONE', ''),
       (2, 'Health Guru', 'You''re making healthy choices! Collect products with Nutri-Score A', 15, 50, 150,
        'NUTRI_SCORE', 'A'),
       (3, 'Living on the Edge', 'We won''t judge! Collect products with Nutri-Score E', 10, 30, 100, 'NUTRI_SCORE',
        'E'),
       (4, 'Gym Bro', 'Do you even lift, bro? Collect protein products', 10, 40, 150, 'PRODUCT_NAME', 'Protein'),
       (5, 'Skinny Bro', 'Keeping it light and keeping it right! Collect light products', 15, 50, 200, 'PRODUCT_NAME',
        'Light'),
       (6, 'Sweet Johnny', 'Your sweet tooth is showing! Collect sweet snacks', 10, 35, 100, 'PRODUCT_CATEGORY',
        'Sweet snacks'),
       (7, 'Nutella Junkie', 'Nobody can resist the chocolatey goodness. Collect Nutella products', 3, 8, 15,
        'PRODUCT_NAME', 'Nutella'),
       (8, 'Juice Master', 'Squeeze the day with your juice collection. Collect juices and nectars', 10, 30, 100,
        'PRODUCT_CATEGORY', 'Juices and nectars'),
       (9, 'Hydration Expert', 'Stay hydrated, my friend! Collect water products', 5, 15, 40, 'PRODUCT_CATEGORY',
        'Waters'),
       (10, 'Bubble Trouble', 'Pop those sodas into your collection. Collect sodas', 8, 25, 75, 'PRODUCT_CATEGORY',
        'Sodas'),
       (11, 'MONSTER', 'Unleash the beast. Collect Monster Energy drinks', 5, 15, 35, 'PRODUCT_NAME', 'Monster Energy'),
       (12, 'Caffeine Addict', 'But first, coffee... lots of coffee. Collect coffee products', 10, 35, 100,
        'PRODUCT_CATEGORY', 'Coffees'),
       (13, 'Dairy Detective', 'On the case of all things dairy. Collect dairy products', 15, 50, 150,
        'PRODUCT_CATEGORY', 'Dairies'),
       (14, 'Milky Dave', 'Got milk? Dave sure does! Collect milk products', 5, 15, 40, 'PRODUCT_CATEGORY', 'Milks'),
       (15, 'Cold Palmer', 'I scream, you scream, we all buy ice cream. Collect ice cream products', 10, 30, 80,
        'PRODUCT_CATEGORY', 'Ice creams'),
       (16, 'Huel Enjoyer', 'Who needs ingredients you can pronounce? Collect ultra-processed products', 15, 50, 100,
        'NOVA_SCORE', '4'),
       (17, 'Nature Fan', 'Reject modernity, embrace tradition. Collect unprocessed products', 15, 50, 100,
        'NOVA_SCORE', '1'),
       (18, 'Booze Beast', 'PhD in Alcohology. Collect alcoholic beverages', 10, 30, 100, 'PRODUCT_CATEGORY',
        'Alcoholic beverages'),
       (19, 'Are you serious?', 'You better not eat that!', 1, 2, 3, 'PRODUCT_NAME', 'Domestos');
